### ISSUE TITLE
when will you publish other chapters?

### ISSUE THREAD

**Issue by wangdepin** [rnorm/book_sample#1]

**Comment by rnorm** [comment]
@wangdepin What would be the topics you are interested in?

**Comment by briatte** [comment]
I'm not the OP, but I'd love to learn how to run statistical models (linear regression, ordinal logit, fixed-effects models, multilevel models, and possibly ERGMs network models and text-data topic models) in Python :)

**Comment by rnorm** [comment]
issue closed
